[package]
name = "zink"
version = "0.1.0"
authors = ["Alexey Shmalko <rasen.dubi@gmail.com>"]

[dependencies]
mqtt-protocol = "0.3"
serde_json = "0.9"
rs-jsonpath = "0.1"
clap = "2"
itertools = "0.5"

bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"